# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 262f8137d853bd07398256cd904586d96ec2690b10047d55891b1180b28f2b31ac322bdfb7171740ff6adaf86b4b1b2f49a42c16899c46b323e4fab05964ecf0

test:
  secret_key_base: 9f447ac6279b01751b5117af2cdcc58d9b29d8132da736246adc8b6417ef4cf0497181d996dbdaa7193dacc92d905be4f459d3302dcbdaa48e4fd865403abd16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
